export const USER_API = {
  URL: "user",
  CLAIM_URL: "/{chain}/claim/",
  REGISTER_URL: "/register",
  CONFIRMATION_URL: "/register/confirm/",
  LOGIN_URL: "/login",
  REQUEST_LOGIN_URL: "/login/{wallet}",
  REQUEST_FIREBASE_LOGIN_URL: "/login/firebase",
  VERIFY_FIREBASE_LOGIN_URL: "/login/firebase/{pin}",
  REQUEST_FIREBASE_REGISTER_URL: "/register/firebase",
  PROFILE_URL: "/profile",
  PROFILE_UPDATE_URL: "/profile/update",
  PROFILE_DETAILS_URL: "/profile/{username}",
  CHECK_PASSWORD_URL: "/password/",
  KYC_URL: "/kyc",
  VERIFY_TWITTER: "/twitter/{campaign}/{name}",
  VERIFY_TELEGRAM: "/tg/{campaign}/{name}",
  WHITELIST: "/whitelist",
  REQUEST_WHITELIST: "/whitelist/{campaign}/{wallet}",
  REQUEST_REFERAL_ID: "/referal/{campaign}/{wallet}",
  SUBSCRIBE_URL: "/email/{email}/subscribe",
  UNSUBSCRIBE_URL: "/email/{email}/unsubscribe",
  REQUEST_REFERAL_AMOUNT: "/referal/{campaign}/{wallet}/amount",
  CONFIRM_EMAIL: "/email/{email}/confirm/{code}",
  RESEND_EMAIL: "/email/{email}/resend",
  REWARD_URL: "/reward",
  REWARD_DETAILS_URL: "/reward/detail"
}
